# ===============================
# PUERTO
# ===============================
server.port=8081

# ===============================
# H2 DATABASE
# ===============================
spring.datasource.url=jdbc:h2:mem:autenticacion-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# ACTUATOR 
# ===============================
management.endpoints.web.exposure.include=*

# ===============================
# LOGGING 
# ===============================
logging.level.org.springframework.security=DEBUG


jwt.secret=MI_CLAVE_SUPER_SEGURA_DE_32_O_MAS_BYTES_MINIMO_123456789
jwt.expiration=3600000

